title: Victor Ortiz
description: Estudiante,Esposo y Esclavo del trabajo.
site_title: 'Victor Ortiz'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Victor
blog_url: VictorOrtizChavez.github.io
email: tcvictorortiz@gmail.com


# absolute or relative
profile_picture: assets/images/perfil.jpg

# Google Analytics ID
google_analytics: 
